version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "token-authorizer"
s3_bucket = "aws-sam-cli-managed-default"
s3_prefix = "token-authorizer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
